using System.Reactive;
using System.Reactive.Linq;
using DynamicData;
using LibGit2Sharp;
using Mutagen.Bethesda.Plugins.Order;
using Mutagen.Bethesda.Synthesis.WPF;
using Mutagen.Bethesda.WPF.Plugins.Order;
using Noggog;
using Noggog.Reactive;
using Noggog.UI;
using ReactiveUI;
using Serilog;
using Synthesis.Bethesda.DTO;
using Noggog.GitRepository;
using Synthesis.Bethesda.Execution.PatcherCommands;
using Synthesis.Bethesda.Execution.Patchers.Git;
using Synthesis.Bethesda.Execution.Patchers.Git.Services;
using Synthesis.Bethesda.GUI.Services.Patchers.Git;
using Synthesis.Bethesda.GUI.ViewModels.Groups;
using Synthesis.Bethesda.GUI.ViewModels.Profiles.Plugins;

namespace Synthesis.Bethesda.GUI.ViewModels.Patchers.TopLevel;

public class PatcherUserSettingsVm : ViewModel
{
    public record Inputs(GetResponse<TargetProject> TargetProject, string? SynthVersion, FilePath MetaPath);
    
    private readonly IInitRepository _initRepository;
    private readonly IProvideRepositoryCheckouts _repoCheckouts;
    private readonly IBuildMetaFileReader _metaFileReader;

    public ReactiveCommand<Unit, Unit> OpenSettingsCommand { get; }

    private readonly ObservableAsPropertyHelper<SettingsConfiguration> _settingsConfiguration;
    public SettingsConfiguration SettingsConfiguration => _settingsConfiguration.Value;

    private readonly ObservableAsPropertyHelper<bool> _settingsOpen;
    public bool SettingsOpen => _settingsOpen.Value;

    private bool _hasBeenRetrieved = false;
    private readonly ObservableAsPropertyHelper<AutogeneratedSettingsVm?> _reflectionSettings;
    public AutogeneratedSettingsVm? ReflectionSettings
    {
        get
        {
            _hasBeenRetrieved = true;
            return _reflectionSettings.Value;
        }
    }

    public delegate PatcherUserSettingsVm Factory(
        bool needBuild,
        IObservable<Inputs> source);
        
    public PatcherUserSettingsVm(
        ILogger logger,
        IProfileLoadOrder loadOrder,
        IProfileSimpleLinkCacheVm linkCacheVm,
        IObservable<Inputs> source,
        bool needBuild,
        IInitRepository initRepository,
        IProvideAutogeneratedSettings autoGenSettingsProvider,
        IProvideRepositoryCheckouts repoCheckouts,
        IGetSettingsStyle getSettingsStyle,
        IModKeyProvider modKeyProvider,
        IExecuteOpenForSettings executeOpenForSettings,
        IPatcherRunnabilityCliState runnabilityCliState,
        IOpenSettingsHost openSettingsHost,
        IBuildMetaFileReader metaFileReader,
        ISchedulerProvider schedulerProvider)
    {
        _initRepository = initRepository;
        _repoCheckouts = repoCheckouts;
        _metaFileReader = metaFileReader;
        var settingsResults = source
            .Select(i =>
            {
                return Observable.Create<(SettingsConfiguration Config, string? ExecutablePath, GetResponse<TargetProject> TargetProject)>(async (observer, cancel) =>
                {
                    observer.OnNext((new SettingsConfiguration(SettingsStyle.None, Array.Empty<ReflectionSettingsConfig>()), null, i.TargetProject));
                    if (i.TargetProject.Failed)
                    {
                        observer.OnCompleted();
                        return;
                    }

                    try
                    {
                        SettingsConfiguration result;
                        string? executablePath;

                        if (needBuild)
                        {
                            // Solution patcher - compile and get
                            var compiled = await getSettingsStyle.CompileAndGetForProject(
                                projectPath: i.TargetProject.Value.ProjPath,
                                cancel: cancel).ConfigureAwait(false);
                            result = compiled.Settings;
                            executablePath = compiled.ExecutablePath;
                        }
                        else
                        {
                            // Git patcher - use pre-compiled executable
                            var meta = _metaFileReader.Read(i.MetaPath);
                            if (meta?.ExecutablePath == null)
                            {
                                logger.Error("ExecutablePath is null in compilation meta at {MetaPath}", i.MetaPath);
                                observer.OnCompleted();
                                return;
                            }

                            executablePath = meta.ExecutablePath;
                            result = await getSettingsStyle.Get(
                                executablePath: meta.ExecutablePath,
                                buildMetaPath: i.MetaPath,
                                cancel: cancel).ConfigureAwait(false);
                        }
                        logger.Information("Settings type: {Result}", result);
                        observer.OnNext((result, executablePath, i.TargetProject));
                    }
                    catch (Exception ex)
                    {
                        logger.Error(ex, "Error checking if patcher can open settings");
                    }
                    observer.OnCompleted();
                });
            })
            .Switch()
            .Replay(1)
            .RefCount();

        _settingsConfiguration = settingsResults
            .Select(x => x.Config)
            .ToGuiProperty(this, nameof(SettingsConfiguration), new SettingsConfiguration(SettingsStyle.None, Array.Empty<ReflectionSettingsConfig>()), schedulerProvider.MainThread, deferSubscription: true);

        OpenSettingsCommand = NoggogCommand.CreateFromObject(
            objectSource: Observable.CombineLatest(
                source,
                this.WhenAnyValue(x => x.SettingsConfiguration),
                (Input, Conf) => (Input, Conf)),
            canExecute: x => x.Input.TargetProject.Succeeded
                             && (x.Conf.Style == SettingsStyle.Open || x.Conf.Style == SettingsStyle.Host),
            execute: async (o) =>
            {
                if (o.Conf.Style == SettingsStyle.Open)
                {
                    var modKey = modKeyProvider.ModKey;
                    if (modKey == null)
                    {
                        logger.Information($"Checking runnability failed: No known ModKey");
                        return;
                    }

                    if (needBuild)
                    {
                        logger.Error("Solution patchers do not support OpenForSettings style");
                        return;
                    }

                    var meta = _metaFileReader.Read(o.Input.MetaPath);
                    if (meta?.ExecutablePath == null)
                    {
                        logger.Error("ExecutablePath is null in compilation meta at {MetaPath}", o.Input.MetaPath);
                        return;
                    }

                    await executeOpenForSettings.Open(
                        executablePath: meta.ExecutablePath,
                        modKey: modKey.Value,
                        cancel: CancellationToken.None,
                        loadOrder: loadOrder.LoadOrder.Items.Select<ReadOnlyModListingVM, IModListingGetter>(lvm => lvm)).ConfigureAwait(false);
                }
                else
                {
                    await openSettingsHost.Open(
                        path: o.Input.TargetProject.Value.ProjPath,
                        cancel: CancellationToken.None,
                        loadOrder: loadOrder.LoadOrder.Items.Select<ReadOnlyModListingVM, IModListingGetter>(lvm => lvm)).ConfigureAwait(false);
                }
                runnabilityCliState.CheckAgain();
            },
            disposable: this);

        _settingsOpen = OpenSettingsCommand.IsExecuting
            .ToGuiProperty(this, nameof(SettingsOpen), schedulerProvider.MainThread, deferSubscription: true);

        _reflectionSettings = settingsResults
            .Select(x =>
            {
                if (x.TargetProject.Failed
                    || x.Config.Style != SettingsStyle.SpecifiedClass
                    || x.Config.Targets.Length == 0
                    // A null executable means the build phase had issues; don't build here just to show settings.
                    || x.ExecutablePath == null)
                {
                    return default(AutogeneratedSettingsVm?);
                }

                return autoGenSettingsProvider.Get(x.Config,
                    targetProject: x.TargetProject.Value,
                    prebuiltExecutablePath: x.ExecutablePath,
                    loadOrder: loadOrder.LoadOrder.Connect().Transform<ReadOnlyModListingVM, IModListingGetter>(x => x),
                    linkCache: linkCacheVm.WhenAnyValue(x => x.SimpleLinkCache));
            })
            .ToGuiProperty<AutogeneratedSettingsVm?>(this, nameof(ReflectionSettings), initialValue: null, schedulerProvider.MainThread, deferSubscription: true);
    }

    public void Persist()
    {
        if (!_hasBeenRetrieved) return;
        ReflectionSettings?.Bundle?.Settings?.ForEach(vm =>
        {
            vm.Persist();
            _initRepository.Init(vm.SettingsFolder);
            using var repo = _repoCheckouts.Get(vm.SettingsFolder);
            repo.Repository.Stage(vm.SettingsSubPath);
            try
            {
                repo.Repository.Commit("Settings changed");
            }
            catch (EmptyCommitException)
            {
            }
        });
    }

    public override void Dispose()
    {
        base.Dispose();
        if (_hasBeenRetrieved)
        {
            ReflectionSettings?.Dispose();
        }
    }
}