using System;
using DynamicData;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Plugins.Order;
using Synthesis.Bethesda;

namespace Mutagen.Bethesda.Synthesis.WPF
{
    public interface IProvideAutogeneratedSettings
    {
        AutogeneratedSettingsVM Get(
            SettingsConfiguration config, 
            string projPath, 
            string displayName,
            IObservable<IChangeSet<IModListingGetter>> loadOrder, 
            IObservable<ILinkCache?> linkCache,
            Action<string> log);
    }

    public class ProvideAutogeneratedSettings : IProvideAutogeneratedSettings
    {
        private readonly IProvideReflectionSettingsBundle _ProvideBundle;

        public ProvideAutogeneratedSettings(IProvideReflectionSettingsBundle provideBundle)
        {
            _ProvideBundle = provideBundle;
        }
        
        public AutogeneratedSettingsVM Get(
            SettingsConfiguration config, 
            string projPath, 
            string displayName,
            IObservable<IChangeSet<IModListingGetter>> loadOrder, 
            IObservable<ILinkCache?> linkCache,
            Action<string> log)
        {
            return new AutogeneratedSettingsVM(
                config, projPath, displayName, loadOrder, linkCache,
                _ProvideBundle, 
                log);
        }
    }
}