using System;
using DynamicData;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Plugins.Order;
using Synthesis.Bethesda;
using Synthesis.Bethesda.Execution.Patchers;

namespace Mutagen.Bethesda.Synthesis.WPF
{
    public interface IProvideAutogeneratedSettings
    {
        AutogeneratedSettingsVm Get(
            SettingsConfiguration config, 
            string projPath, 
            IObservable<IChangeSet<IModListingGetter>> loadOrder, 
            IObservable<ILinkCache?> linkCache);
    }

    public class ProvideAutogeneratedSettings : IProvideAutogeneratedSettings
    {
        private readonly IPatcherNameProvider _nameProvider;
        private readonly IProvideReflectionSettingsBundle _ProvideBundle;

        public ProvideAutogeneratedSettings(
            IPatcherNameProvider nameProvider,
            IProvideReflectionSettingsBundle provideBundle)
        {
            _nameProvider = nameProvider;
            _ProvideBundle = provideBundle;
        }
        
        public AutogeneratedSettingsVm Get(
            SettingsConfiguration config, 
            string projPath, 
            IObservable<IChangeSet<IModListingGetter>> loadOrder, 
            IObservable<ILinkCache?> linkCache)
        {
            return new AutogeneratedSettingsVm(
                config, projPath, _nameProvider.Name, loadOrder, linkCache,
                _ProvideBundle);
        }
    }
}