site_name: Synthesis Documentation
site_url: https://mutagen-modding.github.io/Synthesis/

repo_name: Synthesis
repo_url: https://github.com/Mutagen-Modding/Synthesis

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Mutagen-Modding
    - icon: fontawesome/brands/discord
      link: https://discord.gg/GdKZ3SH

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences 
  - pymdownx.tasklist
  - def_list
  - meta
  - md_in_html
  - attr_list
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - glightbox:
      zoomable: true
      draggable: true

theme:
  name: material
  font:
    text: Inter
  palette:
    primary: custom 
    accent: custom
    scheme: slate
  favicon: mutagen-icon.png
  logo: mutagen-icon.png
  features:
    - content.tooltips
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - navigation.indexes 
    - navigation.path
    
nav:
  - Home: index.md
  - Overview:
    - Installation: Installation.md
    - Typical Usage: Typical-Usage.md
    - Patcher Settings: Patcher-Settings.md
    - Synthesis vs Mutagen: Synthesis-vs-Mutagen.md
    - Multiple Output Targets: Multiple-Output-Targets.md
    - Load Order of Patches: LoadOrder.md
    - Overriding Data Folder Path: DataFolder.md
    - Blacklisting Mods: Blacklisting.md
    - Versioning: Versioning.md
    - .synth Files: Synth-File.md
    - Other Dynamic Mod Generators: Other-Dynamic-Mod-Generators.md
    - Language Settings: Language-Settings.md
    - Synthesis CLI: Synthesis-CLI.md
    - Updating UI: Updating-UI.md
    # - Existing Saves: Existing-Saves.md
    - Starting Into a Specific Profile: Starting-Into-Profile.md
    - FAQs and Troubleshooting: FAQ-and-Troubleshooting.md
    - Sharing Your Setup: Sharing.md
  - Patcher Types:
    - Git Repository: Git-Repository-Patcher.md
    - External Program: External-Program-Patcher.md
    - Local Solution: Local-Solution-Patcher.md
  - Developers:
    - Create a Patcher: devs/Create-a-Patcher.md
    - Coding a Patcher: devs/Coding-a-Patcher.md
    - Configuring a Patcher at Startup: devs/Configuring-a-Patcher-at-Startup.md 
    - Running and Debugging: devs/Running-and-Debugging.md
    - Runnability Checks: devs/Runnability-Checks.md
    - User Input: devs/User-Input.md
    - Internal Data: devs/Internal-Data.md
    - Publishing: devs/Publishing.md
    - Nexus Integration: devs/Nexus-Integration.md
    - Supporting Multiple Games: devs/Supporting-Multiple-Games.md
    - Synthesis Collective: devs/Synthesis-Collective.md
    - Patcher CLI: devs/Patcher-CLI.md