using System.Reactive.Disposables;
using Noggog.WPF;
using ReactiveUI;
using Synthesis.Bethesda.GUI.ViewModels.Patchers.Solution;

namespace Synthesis.Bethesda.GUI.Views;

public class SolutionUserSettingsConfigViewBase : NoggogUserControl<SolutionPatcherVm> { }

public partial class SolutionUserSettingsConfigView : SolutionUserSettingsConfigViewBase
{
    public SolutionUserSettingsConfigView()
    {
        InitializeComponent();
        this.WhenActivated(disposable =>
        {
            this.WhenAnyValue(x => x.ViewModel!.ReloadAutogeneratedSettingsCommand)
                .BindTo(this, x => x.ReloadAutogeneratedSettingsButton.Command)
                .DisposeWith(disposable);
            this.WhenAnyFallback(x => x.ViewModel!.PatcherSettings)
                .BindTo(this, x => x.PatcherSettings.DataContext)
                .DisposeWith(disposable);
        });
    }
}