using System.Reactive.Disposables;
using System.Reactive.Disposables.Fluent;
using Noggog.UI;
using Noggog.WPF;
using ReactiveUI;

namespace Synthesis.Bethesda.GUI.Views;

public partial class SolutionUserSettingsConfigView
{
    public SolutionUserSettingsConfigView()
    {
        InitializeComponent();
        this.WhenActivated(disposable =>
        {
            this.WhenAnyValue(x => x.ViewModel!.ReloadAutogeneratedSettingsCommand)
                .BindTo(this, x => x.ReloadAutogeneratedSettingsButton.Command)
                .DisposeWith(disposable);
            this.WhenAnyFallback(x => x.ViewModel!.PatcherSettings)
                .BindTo(this, x => x.PatcherSettings.DataContext)
                .DisposeWith(disposable);
        });
    }
}