using System.IO.Abstractions;
using Mutagen.Bethesda.Environments.DI;
using Mutagen.Bethesda.StructureMap;
using Mutagen.Bethesda.Synthesis.Versioning;
using Mutagen.Bethesda.Synthesis.WPF;
using Noggog;
using Noggog.Reactive;
using Noggog.WPF;
using Serilog;
using StructureMap;
using Synthesis.Bethesda.Execution.GitRespository;
using Synthesis.Bethesda.Execution.Pathing;
using Synthesis.Bethesda.Execution.Versioning;
using Synthesis.Bethesda.GUI.Profiles.Plugins;
using Synthesis.Bethesda.GUI.Services;
using Synthesis.Bethesda.GUI.Services.Startup;
using Synthesis.Bethesda.GUI.Settings;

namespace Synthesis.Bethesda.GUI
{
    public class Register : Registry
    {
        public Register()
        {
            RegisterBaseLib();
            RegisterCurrentLib();
            RegisterWpfLib();
            RegisterExecutionLib();
            RegisterOther();
            RegisterMutagen();
            RegisterCSharpExt();
        }

        private void RegisterBaseLib()
        {
            Scan(s =>
            {
                s.AssemblyContainingType<IProvideCurrentVersions>(); 
                s.IncludeNamespaceContainingType<IProvideCurrentVersions>();
                s.Convention<SingletonConvention>();
            });
        }

        private void RegisterCurrentLib()
        {
            ForSingletonOf<MainVM>();
            ForSingletonOf<ConfigurationVM>();
            ForSingletonOf<PatcherInitializationVM>();
            ForSingletonOf<ILogger>().Use(Log.Logger);
            ForSingletonOf<ISettingsSingleton>().Use<SettingsSingleton>();
            ForSingletonOf<IShowHelpSetting>().Use<ShowHelpSetting>();
            ForSingletonOf<IConsiderPrereleasePreference>().Use<ConsiderPrereleasePreference>();
            ForSingletonOf<IConfirmationPanelControllerVm>().Use<ConfirmationPanelControllerVm>();
            ForSingletonOf<ISelectedProfileControllerVm>().Use<SelectedProfileControllerVm>();
            ForSingletonOf<IActivePanelControllerVm>().Use<ActivePanelControllerVm>();
            ForSingletonOf<RetrieveSaveSettings>();
            Forward<RetrieveSaveSettings, IRetrieveSaveSettings>();
            Forward<RetrieveSaveSettings, ISaveSignal>();
            
            Scan(s =>
            {
                s.AssemblyContainingType<IEnvironmentErrorVM>();
                s.AddAllTypesOf<IEnvironmentErrorVM>();
            });
            
            Scan(s =>
            {
                s.AssemblyContainingType<INavigateTo>();
                s.IncludeNamespaceContainingType<INavigateTo>();
                s.ExcludeNamespaceContainingType<IStartup>();
                s.WithDefaultConventions();
            });
            
            Scan(s =>
            {
                s.AssemblyContainingType<IStartup>();
                s.IncludeNamespaceContainingType<IStartup>();
                s.Convention<SingletonConvention>();
            });
            
            For<ILockToCurrentVersioning>().Use<LockToCurrentVersioning>();
            For<IProfileDisplayControllerVm>().Use<ProfileDisplayControllerVm>();
            For<IEnvironmentErrorsVM>().Use<EnvironmentErrorsVM>();
            For<ProfilePatchersList>();
            Forward<ProfilePatchersList, IRemovePatcherFromProfile>();
            Forward<ProfilePatchersList, IProfilePatchersList>();
            For<IProfileIdentifier>().Use<ProfileIdentifier>();
            For<IProfileLoadOrder>().Use<ProfileLoadOrder>();
            For<IProfileDirectories>().Use<ProfileDirectories>();
            For<IProfileDataFolder>().Use<ProfileDataFolder>();
            For<IProfileVersioning>().Use<ProfileVersioning>();
            For<IProfileSimpleLinkCache>().Use<ProfileSimpleLinkCache>();
            For<GitPatcherInitVM>();
            For<CliPatcherInitVM>();
            
            // Overrides
            ForSingletonOf<IProvideWorkingDirectory>().Use<WorkingDirectoryOverride>();
        }

        private void RegisterWpfLib()
        {
            Scan(s =>
            {
                s.AssemblyContainingType<IProvideAutogeneratedSettings>();
                s.IncludeNamespaceContainingType<IProvideAutogeneratedSettings>();
                s.WithDefaultConventions();
            });
        }

        private void RegisterExecutionLib()
        {
            Scan(s =>
            {
                s.AssemblyContainingType<ICheckOrCloneRepo>();
                s.ExcludeType<ProvideWorkingDirectory>();
                s.Convention<SingletonConvention>();
            });
        }

        private void RegisterOther()
        {
            For<IFileSystem>().Use<FileSystem>();
        }

        private void RegisterMutagen()
        {
            IncludeRegistry<MutagenRegister>();
            For<IGameReleaseContext>().Use(x => new GameReleasePlaceholder());
        }

        private void RegisterCSharpExt()
        {
            For<ISchedulerProvider>().Use<SchedulerProvider>();
            Scan(s =>
            {
                s.AssemblyContainingType<IWatchFile>();
                s.AssemblyContainingType<ISchedulerProvider>();
                s.ExcludeType<BinaryReadStream>();
                s.ExcludeType<BinaryWriteStream>();
                s.WithDefaultConventions();
            });
        }
    }
}