using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Synthesis.Bethesda
{
    public enum Codes
    {
        NotRunnable = 1753,
        OpensForSettings = 1754,
        AutogeneratedSettingsClass = 1755,
        Unsupported = -1,
    }
}
