using System.IO.Abstractions;
using Autofac;
using Mutagen.Bethesda.Autofac;
using Mutagen.Bethesda.Synthesis.Projects;
using Mutagen.Bethesda.Synthesis.Versioning;
using Mutagen.Bethesda.Synthesis.WPF;
using Noggog.Autofac;
using Noggog.Reactive;
using Noggog.Utility;
using Noggog.WPF;
using Serilog;
using Synthesis.Bethesda.Execution.CLI;
using Synthesis.Bethesda.Execution.DotNet;
using Synthesis.Bethesda.Execution.GitRespository;
using Synthesis.Bethesda.Execution.Patchers.Git;
using Synthesis.Bethesda.Execution.Pathing;
using Synthesis.Bethesda.Execution.Running;
using Synthesis.Bethesda.Execution.Versioning;
using Synthesis.Bethesda.GUI.Services.Main;
using Synthesis.Bethesda.GUI.Services.Startup;
using Synthesis.Bethesda.GUI.Settings;
using Synthesis.Bethesda.GUI.ViewModels.Patchers;

namespace Synthesis.Bethesda.GUI.DI
{
    public class TopLevelModule : Module
    {
        protected override void Load(ContainerBuilder builder)
        {
            builder.RegisterType<FileSystem>().As<IFileSystem>()
                .SingleInstance();
            builder.RegisterType<ProcessFactory>().As<IProcessFactory>()
                .SingleInstance();
            builder.RegisterInstance(Log.Logger).As<ILogger>();
            
            // Noggog
            builder.RegisterType<WatchFile>().As<IWatchFile>()
                .SingleInstance();
            builder.RegisterType<WatchDirectory>().As<IWatchDirectory>()
                .SingleInstance();
            builder.RegisterType<SchedulerProvider>().As<ISchedulerProvider>()
                .SingleInstance();
            
            // Mutagen
            builder.RegisterModule<MutagenModule>();
            
            // Mutagen.Bethesda.Synthesis
            builder.RegisterAssemblyTypes(typeof(IProvideCurrentVersions).Assembly)
                .InNamespacesOf(
                    typeof(IProvideCurrentVersions),
                    typeof(ICreateProject))
                .AsMatchingInterface()
                .SingleInstance();
            
            // Mutagen.Bethesda.Synthesis.WPF
            builder.RegisterAssemblyTypes(typeof(IProvideAutogeneratedSettings).Assembly)
                .InNamespaceOf<IProvideAutogeneratedSettings>()
                .AsMatchingInterface();
            
            // Synthesis.Bethesda.Execution
            builder.RegisterAssemblyTypes(typeof(ICheckOrCloneRepo).Assembly)
                .InNamespacesOf(
                    typeof(ICheckOrCloneRepo),
                    typeof(IQueryNewestLibraryVersions),
                    typeof(IInstalledSdkProvider))
                .AsMatchingInterface()
                .SingleInstance();
            builder.RegisterAssemblyTypes(typeof(ICheckOrCloneRepo).Assembly)
                .InNamespacesOf(
                    typeof(IWorkingDirectorySubPaths),
                    typeof(IRunner),
                    typeof(ICheckoutRunnerRepository),
                    typeof(ICheckRunnability))
                .Except<ProvideWorkingDirectory>()
                .AsMatchingInterface();
            
            // GUI
            builder.RegisterType<MainVm>().AsSelf().SingleInstance();
            builder.RegisterType<ConfigurationVm>().AsSelf().SingleInstance();
            builder.RegisterType<PatcherInitializationVm>().AsSelf().SingleInstance();
            builder.RegisterType<ConfirmationPanelControllerVm>().As<IConfirmationPanelControllerVm>().SingleInstance();
            builder.RegisterType<SelectedProfileControllerVm>().As<ISelectedProfileControllerVm>().SingleInstance();
            builder.RegisterType<EnvironmentErrorsVm>().As<IEnvironmentErrorsVm>().SingleInstance();
            builder.RegisterType<ActivePanelControllerVm>().As<IActivePanelControllerVm>().SingleInstance();
            builder.RegisterAssemblyTypes(typeof(INavigateTo).Assembly)
                .InNamespacesOf(
                    typeof(INavigateTo),
                    typeof(IStartup),
                    typeof(ISynthesisGuiSettings))
                .AsImplementedInterfaces()
                .SingleInstance();
        }
    }
}